apiVersion: v1
kind: ServiceAccount
metadata:
  name: "csrctrl-{{ .Release.Name }}"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: "csrctrl-{{ .Release.Name }}"
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/selfnodeserver
  - certificatesigningrequests/approval
  - certificatesigningrequests
  verbs:
  - list
  - update
  - create
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "csrctrl-{{ .Release.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "csrctrl-{{ .Release.Name }}"
subjects:
- kind: ServiceAccount
  name: "csrctrl-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace | quote }}